#配置
oauthCenterIp: localhost
mysqlIp: 192.168.0.6


logging:
  path: ../logs
  level:
    root: info
feign:
  hystrix:
    enabled: false
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000
security:
  oauth2:
    resource:
      user-info-uri: http://${oauthCenterIp}:5781/uaa/current
      id: ${spring.application.name:}
    client:
      clientId: server
      clientSecret: server
      accessTokenUri: http://${oauthCenterIp}:5781/uaa/oauth/token
      userAuthorizationUri: http://${oauthCenterIp}:5781/uaa/oauth/authorize
      grant-type: client_credentials
      scope: server
spring:
  data:
    elasticsearch:
      cluster-nodes: 192.168.0.6:9200
#  rabbitmq:
#    host: 192.168.3.78
#    port: 5672
#    username: admin
#    password: admin
  sleuth:
    sampler:
      percentage: 1
  datasource:
    url: jdbc:mysql://${mysqlIp}:3306/knowledge?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: knowledge
    password: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart.max-file-size: 100Mb
    multipart.max-request-size: 100Mb
  jpa:
    database: MYSQL
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      timeout: 0
      pool:
        max-active: 200
        max-wait: -1ms
        min-idle: 0




swagger2:
  enable: true
#  base-package: com.honvay.cola
#  title : Cola-Cloud
#  description: Cola cloud Restful API docs
#  termsOfServiceUrl : http://localhost:4000
#  version: 1.0
#  apiName: Authorization
#  apiKeyName: Authorization

#mybatis配置
#mybatis-plus:
#  global-config:
#    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
#    db-column-underline: false
#    refresh-mapper: true
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: true #配置的缓存的全局开关
#    lazyLoadingEnabled: true #延时加载的开关
#    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include:
          refresh,health,info
eureka:
  instance:
    health-check-url-path: /health
    status-page-url-path: /info
    metadata-map:
      management.context-path: ${server.context-path:}

