server:
  servlet:
    context-path: /uaa
  port: 5781

cola:
  wechat:
    miniapp:
      appid: ${COLA_WECHAT_MINIAPP_APPID}
      secret: ${COLA_WECHAT_MINIAPP_SECRET}

spring:
  redis:
    database: 2