server:
  servlet:
    context-path: /dictionary
  port: 5788

logging:
  config: classpath:logback-spring.xml

knowledge:
  staticFileIp: http://192.168.3.78
  dictionary:
    basepath: knowledge
    languagePairPath: languagePairFile
    professionalImgPath: professionalImg
    articleImgPath: articleImg
    ueditorPath: ueditor
    termMarkFilePath: termMarkFile
    excel-path: scrapyExcel

spring:
  redis:
    database: 1
fastjson:
  enable: true